### ISSUE TITLE
correct calculation of the number of points in xaxis

### ISSUE THREAD

**Issue by atravert** [qedsoftware/brukeropusreader#8]
The last fix (5f2ecbf) is a wrong solution to the mismatch between the number of elements of "AB" and NPT, leading to a frequency shift of the whole spectrum
When there is a mismatch, the number of elements of "AB" exeeding NPT are null values and should not be considered as part of the spectrum. 

You could consider this commit:  e095621

I have checked (on one sample file)  that this fix yields spectra not shifted with respect to  the frequencies observed in OPUS.

Best,
Arnaud

**Comment by tdyczek** [comment]
Hello @atravert!
Thanks for an insight, it looks very reasonable.
We will try to check if that holds true for a bigger database of spectra - https://registry.opendata.aws/afsis/ 33 000 of samples and our own data.

**Comment by tdyczek** [comment]
Yes, it looks fine. We would like to merge this.

I've seen you made some changes to your fork of _brukeropusreader_ -  https://github.com/spectrochempy/brukeropusreader

Maybe we should consider syncing our repos? We are happy to merge your changes - both this bugfix and travis/conda config. Otherwise our repos will get out of sync and we both may miss some changes. What do you think?

**Comment by atravert** [comment]
Dear Tomasz

I am happy to know it worked for your large database of spectra !   (by the way: it is not my concern, but you might consider using [zenodo](https://about.zenodo.org/)  instead of amazon' AWS)

And yes, I will make a pull request to your master branch.
Best,
Arnaud

**Comment by tdyczek** [comment]
Thanks, great!

Regards,
Tomasz

**Comment by mlazowik** [comment]
@atravert thanks for linking to zenodo! We'll look into that once we start publishing more datasets/papers.
